setwd("E:/Computer Engg/Machine learning/RScripts/RestaurantRevenue");
train<-read.csv("train.csv")
test<-read.csv("test.csv")
train$date <- strptime(train$Open.Date, "%m/%d/%Y")
train$date <- as.POSIXct(train$Open.Date, format="%m/%d/%Y")
train$Month <- factor(format(train$date, "%m"))
train$Year <- factor(format(train$date, "%Y"))
train$Day <- factor(format(train$date,"%d"))
train$date<-NULL

test$date <- strptime(test$Open.Date, "%m/%d/%Y")
test$date <- as.POSIXct(test$Open.Date, format="%m/%d/%Y")
test$Month <- factor(format(test$date, "%m"))
test$Year <- factor(format(test$date, "%Y"))
test$Day <- factor(format(test$date,"%d"))
test$date<-NULL
str(train)
#unique(train$City)
#library(caret,lib.loc= "C:/Users/Prajwala/AppData/Local/Temp/RtmpOGSWXx/downloaded_packages")
#dmy <- dummyVars(" ~ .", data = train, fullRank=T)
#train <- data.frame(predict(dmy, newdata = train))
train$City = as.numeric(factor(train$City))
test$City= as.numeric(factor(test$City))

train$City.Group= as.numeric(factor(train$City.Group))
test$City.Group=as.numeric(factor(test$City.Group))

train$Type=as.numeric(factor(train$Type))
test$Type=as.numeric(factor(test$Type))

#install.packages("devtools")
#library("devtools",lib.loc = "C:/Users/Prajwala/AppData/Local/Temp/RtmpkLl0bK/downloaded_packages")
#install_github('xgboost','tqchen',subdir='R-package')
#install.packages("drat", repos="https://cran.rstudio.com")
#drat:::addRepo("dmlc")
#install.packages("xgboost")
#library("xgboost")#, lib.loc="C:/Users/Prajwala/AppData/Local/Temp/RtmpkLl0bK/downloaded_packages")
#install.packages("devtools")
#devtools::install_github("dmlc/xgboost", subdir = "R-package")
#install.packages("ggplot2")
#install.packages("Ckmeans.1d.dp")
#demo(package = "xgboost")
#demo("basic_walkthrough", package = "xgboost")
library(xgboost)
print(names(train))
outcome = c('revenue')
predictors = names(train)[!names(train) %in% outcome]
print(predictors)
print(colnames(train))
set.seed(121)
bst <- xgboost(data = as.matrix(train[,predictors]),label = train[,outcome], nround=10,objective = "reg:linear")
first_model = xgboost(data = as.matrix(train$data), label = train$label,eta = 1, nthread = 2, nround = 2,objective = "reg:linear")
str(train)
prediction = predict(first_model,test$data)
print(prediction)
head(prediction)
