setwd("E:/Computer Engg/Machine learning/RScripts/CoverType");
library(xgboost)
train<-read.csv("train.csv");
test<-read.csv("test.csv")
classes<-as.numeric(train$Cover_Type)
classes<-classes-1
print(classes)
train$Elevation<-as.numeric(train$Elevation)
print(test)
data<-as.matrix(train[2:56])
test$Elevation<-as.numeric(test$Elevation)
data2<-as.matrix(test)
unique(classes)
dtrain<-xgb.DMatrix(data=data,label=classes)
watchlist <- list(train=dtrain)
bst <- xgb.train(data=dtrain, max.depth=10,num_class=7, eta=0.01, nthread = 2, nround=2, watchlist=watchlist, objective = "multi:softprob")
dtest<-xgb.DMatrix(data=data2)
#predictions = predict(bst,dtest)
#probs<-t(matrix(predictions,nrow=7,ncol=length(predictions)/7))
#print(head(probs))
prob <- matrix(predict(bst, dtest), ncol = 7, byrow = T)
answer<-max.col(prob,'first')
confusionMatrix(factor(y+1), factor(answer))
print(answer)
unique(answer)
